const TYPES = {
  Scene: Symbol.for('Scene'),
  SceneManager: Symbol.for('SceneManager'),
  InstanceManager: Symbol.for('InstanceManager'),
  CameraController: Symbol.for('CameraController'),
  LevelGenerator: Symbol.for('LevelGenerator'),
  Random: Symbol.for('Random'),
  GameParams: Symbol.for('GameParams'),
  PlayerEventManager: Symbol.for('PlayerEventManager'),
  EventManager: Symbol.for('EventManager'),
  GUI: Symbol.for('GUI'),
  MovementController: Symbol.for('MovementController'),
  OrientationController: Symbol.for('OrientationController'),
  CollisionController: Symbol.for('CollisionController'),
  KeyboardManager: Symbol.for('KeyboardManager'),
  Ufo: Symbol.for('Ufo'),
  Player: Symbol.for('Player'),
  Planet: Symbol.for('Planet'),
  Main: Symbol.for('Main'),
  Http: Symbol.for('Http'),
  MatchmakingSocket: Symbol.for('MatchmakingSocket'),
  PlayerDataController: Symbol.for('PlayerDataController'),
  MatchSocket: Symbol.for('MatchSocket'),
  PlanetFactory: Symbol.for('Factory<Planet>'),
  PlayerFactory: Symbol.for('Factory<Player>'),
  UfoFactory: Symbol.for('Factory<Ufo>'),
};

export default TYPES;
