const TYPES = {
  Scene: Symbol.for('Scene'),
  SceneSync: Symbol.for('SceneSync'),
  SceneManager: Symbol.for('SceneManager'),
  InstanceManager: Symbol.for('InstanceManager'),
  CameraController: Symbol.for('CameraController'),
  LevelGenerator: Symbol.for('LevelGenerator'),
  Random: Symbol.for('Random'),
  GameParams: Symbol.for('GameParams'),
  PlayerEventManager: Symbol.for('PlayerEventManager'),
  EventManager: Symbol.for('EventManager'),
  GUI: Symbol.for('GUI'),
  GUIManager: Symbol.for('GUIManager'),
  MatchGUI: Symbol.for('MatchGUI'),
  MenuGUI: Symbol.for('MenuGUI'),
  MovementController: Symbol.for('MovementController'),
  OrientationController: Symbol.for('OrientationController'),
  CollisionController: Symbol.for('CollisionController'),
  KeyboardManager: Symbol.for('KeyboardManager'),
  Ufo: Symbol.for('Ufo'),
  Player: Symbol.for('Player'),
  Planet: Symbol.for('Planet'),
  Main: Symbol.for('Main'),
  Http: Symbol.for('Http'),
  MatchmakingSocket: Symbol.for('MatchmakingSocket'),
  PlayerDataController: Symbol.for('PlayerDataController'),
  MatchSocket: Symbol.for('MatchSocket'),
  PlayerStateSocket: Symbol.for('PlayerStateSocket'),
  MenuScene: Symbol.for('MenuScene'),
  GameScene: Symbol.for('GameScene'),
  PlayerStateSocketFactory: Symbol.for('Factory<PlayerStateSocketFactory>'),
  SceneFactory: Symbol.for('SceneFactory'),
  PlanetFactory: Symbol.for('Factory<Planet>'),
  PlayerFactory: Symbol.for('Factory<Player>'),
  UfoFactory: Symbol.for('Factory<Ufo>'),
  UfoManager: Symbol.for('UfoManager'),
};

export default TYPES;
